"""

Model Configurations

"""

TASK3_A_BERT = {
    "name": "TASK3_A",
    "token_type": "bert",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "ntua_twitter_300",
    "embed_dim": 300,
    "embed_finetune": False,
    "embed_noise": 0.05,
    "embed_dropout": 0.1,
    "encoder_dropout": 0.2,
    "encoder_size": 150,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.7,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}


TASK3_A = {
    "name": "TASK3_A",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "glove.twitter.27B.200d",
    "embed_dim": 200,
    "embed_finetune": False,
    "embed_noise": 0.4,
    "embed_dropout": 0.2,
    "encoder_dropout": 0.4,
    "encoder_size": 200,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.7,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}

TASK3_B = {
    "name": "TASK3_B",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "ntua_twitter_300",
    "embed_dim": 300,
    "embed_finetune": False,
    "embed_noise": 0.4,
    "embed_dropout": 0.2,
    "encoder_dropout": 0.4,
    "encoder_size": 150,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.3,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}


TASK3_A_REC = {
    "name": "TASK3_A",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "glove.twitter.27B.200d",
    "embed_dim": 200,
    "embed_finetune": False,
    "embed_noise": 0.3,
    "embed_dropout": 0.2,
    "encoder_dropout": 0.2,
    "encoder_size": 200,
    "encoder_layers": 4,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.7,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
    "attention_heads": 10,
    "recurrent_steps": 5,
}

TASK3_B_REC = {
    "name": "TASK3_B",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "ntua_twitter_300",
    "embed_dim": 300,
    "embed_finetune": False,
    "embed_noise": 0.2,
    "embed_dropout": 0.1,
    "encoder_dropout": 0.2,
    "encoder_size": 150,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.3,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}


SEMEVAL_2017 = {
    "name": "SEMEVAL_2017",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
   "epochs": 50,
    "embeddings_file": "ntua_twitter_affect_310",
    "embed_dim": 310,
    "embed_finetune": False,
    "embed_noise": 0.2,
    "embed_dropout": 0.1,
    "encoder_dropout": 0.3,
    "encoder_size": 150,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 2,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.3,
    "base": 0.68,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}


TASK_A_2019 = {
    "name": "TASK_A_2019",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "glove.twitter.27B.200d",
    "embed_dim": 200,
    "embed_finetune": True,
    "embed_noise": 0.3,
    "embed_dropout": 0.2,
    "encoder_dropout": 0.4,
    "encoder_size": 150,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.3,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}

TASK_B_2019 = {
    "name": "TASK_B_2019",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "glove.twitter.27B.200d",
    "embed_dim": 200,
    "embed_finetune": True,
    "embed_noise": 0.3,
    "embed_dropout": 0.25,
    "encoder_dropout": 0.4,
    "encoder_size": 25,
    "encoder_layers": 3,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.3,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}


TASK_C_2019 = {
    "name": "TASK_C_2019",
    "token_type": "word",
    "batch_train": 32,
    "batch_eval": 32,
    "epochs": 50,
    "embeddings_file": "glove.twitter.27B.200d",
    "embed_dim": 200,
    "embed_finetune": True,
    "embed_noise": 0.3,
    "embed_dropout": 0.2,
    "encoder_dropout": 0.4,
    "encoder_size": 100,
    "encoder_layers": 2,
    "encoder_bidirectional": True,
    "attention": True,
    "attention_layers": 1,
    "attention_context": False,
    "attention_activation": "tanh",
    "attention_dropout": 0.0,
    "base": 0.3,
    "patience": 10,
    "weight_decay": 0.0,
    "clip_norm": 1,
}